"""Change Reaction model

Revision ID: 0862e371d2be
Revises: 0fe935ab9ff7
Create Date: 2022-03-29 19:09:09.639129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0862e371d2be'
down_revision = '0fe935ab9ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
