"""[ADD] cascade

Revision ID: 0bb5a337bcfc
Revises: d90795baba36
Create Date: 2021-09-05 16:29:12.866717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb5a337bcfc'
down_revision = 'd90795baba36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
