"""[ADD] RoomUnseenMessage model

Revision ID: 0def36ed882f
Revises: bb52767be1b5
Create Date: 2021-11-02 11:17:51.592318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0def36ed882f'
down_revision = 'bb52767be1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomUnseenMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message'], ['roomchatmessage.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomUnseenMessage')
    # ### end Alembic commands ###
