"""add new column in Reaction model

Revision ID: 0fe935ab9ff7
Revises: 8ec9b0e66228
Create Date: 2022-03-20 21:18:26.665785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe935ab9ff7'
down_revision = '8ec9b0e66228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
