"""[ADD] RoomChatMessage model 

Revision ID: 481a96b331ef
Revises: a0ad0d112046
Create Date: 2021-09-01 17:57:55.587347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481a96b331ef'
down_revision = 'a0ad0d112046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomchatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['privatechatroom.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomchatmessage')
    # ### end Alembic commands ###
