"""[ADD] dafault time

Revision ID: 844b2e827fcf
Revises: 481a96b331ef
Create Date: 2021-09-01 21:14:51.210363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844b2e827fcf'
down_revision = '481a96b331ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
