"""change react to reacts in Feed model

Revision ID: 8ec9b0e66228
Revises: c475b0d1cf3d
Create Date: 2022-03-18 23:26:36.067317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec9b0e66228'
down_revision = 'c475b0d1cf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
