"""[MOD] RoomChatMessage timestamp 2.0

Revision ID: c7a185948b6c
Revises: d93ad672a0cd
Create Date: 2022-04-06 23:47:23.570050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a185948b6c'
down_revision = 'd93ad672a0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="roomchatmessage",
                    column_name="timestamp",
                    type_=sa.DateTime,
                    existing_type=sa.Date
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
