"""[ADD] change foreign key

Revision ID: d61611253d32
Revises: 0bb5a337bcfc
Create Date: 2021-09-05 16:37:05.585755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61611253d32'
down_revision = '0bb5a337bcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
