"""[ADD] cascade

Revision ID: d90795baba36
Revises: 844b2e827fcf
Create Date: 2021-09-05 16:23:15.339267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90795baba36'
down_revision = '844b2e827fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roomchatmessage_user_fkey', 'roomchatmessage', type_='foreignkey')
    op.create_foreign_key(None, 'roomchatmessage', 'users', ['user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roomchatmessage', type_='foreignkey')
    op.create_foreign_key('roomchatmessage_user_fkey', 'roomchatmessage', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
