"""[MOD] RoomChatMessage timestamp

Revision ID: d93ad672a0cd
Revises: 0862e371d2be
Create Date: 2022-04-06 23:13:37.992997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93ad672a0cd'
down_revision = '0862e371d2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="roomchatmessage",
                    column_name="timestamp",
                    type_=sa.DateTime,
                    existing_type=sa.Date
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
